---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/]
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: stock-db-postgres
images:
  - name: stock-db-postgres
    newName: stock-db-postgres
    newTag: latest
